### PR TITLE
Active Waste Type fetch from backend

### PR DESCRIPTION
**Pull request by BeefyAdmiral**

### CODE REVIEW

**Review by paulgray01 — APPROVED** [review]
looks good

**Comment by paulgray01** [comment]
made piechart use waste type fetch data as well

**Comment by tzjg7293** [comment]
Wow how did you do this?/

**Comment by tzjg7293** [comment]
SO good

**Comment by tzjg7293** [comment]
Nice job Anshul

**Comment by tzjg7293** [comment]
Wow how did you do this?

**Pull request merged**
