### PR TITLE
Changes added to frontend

### PR DESCRIPTION
**Pull request by BeefyAdmiral**

### CODE REVIEW

**Comment by BeefyAdmiral** [comment]
It's over 20000!

**Review by mitchelhussack — APPROVED** [review]
You're the new sydney with all these changes! I like it

**Comment by tzjg7293** [comment]
Hahah!!!

**Comment by tzjg7293** [comment]
We don't even have to bother telling the TAs I think they understand by now LOL

**Review by paulgray01 — APPROVED** [review]
looks good

**Comment by paulgray01** [comment]
Seems to still work with updated package-lock, ill copy mine in case though

**Pull request merged**
