### PR TITLE
home page basic layout

### PR DESCRIPTION
**Pull request by tzjg7293**

### CODE REVIEW

**Comment by tzjg7293** [comment]
Guys let me know if the module runs for you

**Comment by tzjg7293** [comment]
by that I mean the npm/node module

**Comment by tzjg7293** [comment]
Like see if you can run and see the home page.

**Comment by tzjg7293** [comment]
The home page should be pretty much done at least (look wise)

**Review by paulgray01 — APPROVED** [review]
ok

**Pull request merged**
