### PR TITLE
Landing page styling and documentation

### PR DESCRIPTION
**Pull request by paulgray01**
Landing page styling and documentation

### CODE REVIEW

**Review by mitchelhussack — APPROVED** [review]
Looks good

**Review by BeefyAdmiral — APPROVED** [review]
*click* noice

**Comment by mitchelhussack** [comment]
Beautiful

**Comment by BeefyAdmiral** [comment]
Last one promise

**Comment by BeefyAdmiral** [comment]
Sike! Another one!

**Pull request merged**
