### PR TITLE
Client Meeting Minutes 2023-01-25

### PR DESCRIPTION
**Pull request by paulgray01**
created Client Meeting Minutes for 2023-01-25

Issues:
- #38

### CODE REVIEW

**Comment by tzjg7293** [comment]
Looks good Paul!

**Comment by tzjg7293** [comment]
Thanks for taking the minute

**Comment by tzjg7293** [comment]
This will be good when we talk to Gema about our issues with the client

**Review by tzjg7293 — APPROVED** [review]
looks good thanks Paul!

**Review by mitchelhussack — APPROVED** [review]
Exquisite

**Pull request merged**
